# Generated by Django 2.2.11 on 2022-01-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220124_0339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='image',
            new_name='input_image',
        ),
        migrations.AddField(
            model_name='images',
            name='output_image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
