# Generated by Django 2.2.11 on 2022-01-24 04:05

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220124_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='input_image',
            field=models.ImageField(upload_to=home.models.image_name),
        ),
        migrations.AlterField(
            model_name='images',
            name='output_image',
            field=models.ImageField(blank=True, upload_to=home.models.image_name),
        ),
    ]
