# Generated by Django 2.2.11 on 2022-01-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220124_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='create',
            field=models.BooleanField(default=False),
        ),
    ]
