# Generated by Django 2.2.11 on 2022-01-27 07:09

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_images_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='resized_input_image',
            field=models.ImageField(blank=True, upload_to=home.models.image_name),
        ),
        migrations.AddField(
            model_name='images',
            name='resized_output_image',
            field=models.ImageField(blank=True, upload_to=home.models.image_name),
        ),
    ]
